server:
  port: 9999
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 10240000
  max-http-header-size: 10240000
spring:
  resources:
    static-locations: classpath:static/,file:static/
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    data-username: root
    data-password: apy
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

